version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
sphinx:
  configuration: abqpy/docs/source/conf.py
formats: []
python:
  install:
    - requirements: requirements.txt
    - requirements: abqpy/requirements.txt
    - requirements: abqpy/docs/requirements.txt
submodules:
  include:
    - abqpy
