version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - cd abqpy
      - python setup.py install
      - pip install -r ./requirements.txt
      - pip install -r ./docs/requirements.txt
      - cd ..
sphinx:
  configuration: abqpy/docs/source/conf.py
formats: []
python:
  install:
    - requirements: requirements.txt
