version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install abqpy
      - pip install -r abqpy/requirements.txt
      - pip install -r abqpy/docs/requirements.txt
sphinx:
  configuration: abqpy/docs/source/conf.py
formats: []
python:
  install:
    - requirements: requirements.txt
submodules:
  include:
    - abqpy
