name: update-translations

on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
  workflow_dispatch:

jobs:
  update-translations:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [main, V2022, V2021, V2020, V2019, V2018, V2017, V2016]
    env:
      SPHINXINTL_TRANSIFEX_PROJECT_NAME: abqpy
      SPHINXINTL_TRANSIFEX_USERNAME: hailin
      SPHINXINTL_TRANSIFEX_PASSWORD: ${{ secrets.SPHINXINTL_TRANSIFEX_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Get date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        echo "::set-output name=yyyymm::$(/bin/date -u "+%Y%m")"
      shell: bash
    - name: cache pip
      id: cache-pip
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.local/
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ steps.get-date.outputs.yyyymm }}
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Check Python version
      run: python --version
    - name: Install dependencies
      run: |
        git fetch origin
        git checkout origin/main
        git checkout ${{ matrix.branch }}  # attach this repo
        git submodule init
        git submodule update
        (cd abqpy; git fetch origin; git checkout main; git reset --hard origin/${{ matrix.branch }}; git branch -a; pip install -r ./docs/requirements.txt; pip install .)
        pip install -U pip setuptools
        pip install -r ./requirements.txt
    - name: Update translations
      run: sh ./locales/update.sh
    - name: After success
      run: |
        git branch -a
        git checkout ${{ matrix.branch }}  # attach this repo
        git config --global user.email "abqpy-auto-update"
        git config --global user.name "abqpy-auto-update"
        git add .
        git commit -m "[skip ci] by GHA https://github.com/${{ github.repository }}/actions/runs/${{ github.run_number }}"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ matrix.branch }}